### ISSUE TITLE
工具栏上的默认字体、默认字号、默认行高怎么换成 icon 或 自定义名称

### ISSUE THREAD

**Issue by lixiaojian** [wangeditor-team/wangEditor-for-react#12]
工具栏上的默认字体、默认字号、默认行高怎么换成 icon 或 自定义名称 ，这几个名字太长了，太占位置了，差不多点了三分之一的工具栏宽度，但又需要用到。可不可以换成图标或自定义 title

**Comment by wangfupeng1988** [comment]
目前不支持配置 title 和 icon

可以参考这个 issue https://github.com/wangeditor-team/wangEditor/issues/4555

**Comment by lixiaojian** [comment]
感谢，搞定
```javascript
import { i18nGetResources } from '@wangeditor/editor';
i18nGetResources('zh-CN').lineHeight.default='行高';
i18nGetResources('zh-CN').fontFamily.default='字体';
i18nGetResources('zh-CN').fontSize.default='字号';
```
```less
.w-e-bar-item{
  flex: 1;
  button {
    padding: 0 2px;
  }
  .select-button{
    width: auto !important;
  }
}
```
